nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_credentials: true
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
